# Default configuration.

# General info used by Actuator in the /info endpoint.
info:
  build:
    version: @project.version@
    artifactId: @project.artifactId@
    groupId: @project.groupId@
    name: discovery-server
    description: ${info.build.name} is the configuration server in the cloud.

# Server.
server:
  port: 8888 # The standard port for Cloud Config.
  compression:
    enabled: true # Enable compression for html, xml, css and plain text.

# Actuator.
management:
  endpoints:
    web:
      base-path: /actuator
      enabled-by-default: true
      exposure:
        include: "*"
        exclude: shutdown
  metrics:
    web:
      server:
        auto-time-requests: true

# Eureka discovery server.
eureka:
  client:
    # Both false to avoid this error: "Cannot execute request on any known server".
    registerWithEureka: false # Whether the server will try to register itself as a client.
    fetchRegistry: false # True to get the Eureka registry on startup.

# Spring Framework properties.
spring:

  cloud:
    config:
      server:
        git:
          # No need of credentials since the repo is public for reading.
          uri: https://github.com/apinazo/cloudsample.git
          clone-on-start: true

# Hardcoded user for Spring Security.
security:
  user:
    name: root
    password: password # TODO: Remove and replace by an env var at runtime.

