# Default configuration.

# General info used by Actuator in the /info endpoint.
info:
  build:
    version: @project.version@
    artifactId: @project.artifactId@
    groupId: @project.groupId@
    name: config-server
    description: ${info.build.name} is the configuration server in the cloud.

# Server.
server:
  port: 8888 # The standard port for Cloud Config.
  compression:
    enabled: true # Enable compression for html, xml, css and plain text.

# Actuator.
management:
  endpoints:
    web:
      base-path: /actuator
      enabled-by-default: true
      exposure:
        include: "*"
        exclude: shutdown
  metrics:
    web:
      server:
        auto-time-requests: true

# Spring Framework properties.
spring:
  cloud:
    config:
      server:
        git:
          # No need of credentials since the repo is public for reading.
          # It's not necessary - nor convenient - to add the .git suffix.
          uri: https://github.com/apinazo/config-repo
          clone-on-start: true

# Logging configuration.
logging:
  level:
    es.apinazo: TRACE
    root: INFO
  file: /var/log/cloudsample/config.log
  file.max-history: 1
  file.max-size: 2MB
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
