# Default configuration.

# General info used by Actuator in the /info endpoint.
info:
  build:
    name: greetins-service
    description: ${info.build.name} is a very simple service in the cloud.

# Server
server:
  port: 0 # Use a random port so there can be several instances running at the same time.

# Spring properties
spring:

  # Logs.
  output:
    ansi:
      # Although this is a common property between all apps, cannot be in the config server
      # because it has to be set before getting configurations from it.
      enabled: ALWAYS

# Logging configuration.
logging:
  file: /var/log/cloudsample/greetings.log # If have a value, logs will be written to this file.
