# Default configuration.

# General info used by Actuator in the /info endpoint.
info:
  build:
    version: @project.version@
    artifactId: @project.artifactId@
    groupId: @project.groupId@
    name: greetins-service
    description: ${info.build.name} is a very simple service in the cloud.

# Server
server:
  port: 0 # Use a random port so there can be several instances running at the same time.
  compression:
    enabled: true # Enable compression for html, xml, css and plain text.

# Actuator.
management:
  endpoints:
    web:
      base-path: /actuator
      enabled-by-default: true
      exposure:
        include: "*"
        exclude: shutdown
  metrics:
    web:
      server:
        auto-time-requests: true

# Spring properties.
spring:

  # Logs.
  output:
    ansi:
      enabled: ALWAYS

# Logging configuration.
logging:
  level:
    es.apinazo: TRACE # Level by package.
    root: INFO # Global level for anything that doesn't match the level by package.
  # file properties cannot be nested as all of them has values. Dot notation must be used.
  file: /var/log/cloudsample/greetings.log # If have a value, logs will be written to this file.
  file.max-history: 1 # Maximum of archive log files to keep.
  file.max-size: 2MB # Maximum log file size.
  pattern:
    # Same pattern as the colorful default logs.
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"