# Default configuration.

# General info used by Actuator in the /info endpoint.
info:
  build:
    version: @project.version@
    artifactId: @project.artifactId@
    groupId: @project.groupId@
    name: monitor
    description: ${info.build.name} takes care of the cloud, using Spring Boot Admin.

# Server
server:
  port: 7777
  compression:
    enabled: true # Enable compression for html, xml, css and plain text.

# Actuator.
management:
  endpoints:
    web:
      base-path: /actuator
      enabled-by-default: true
      exposure:
        include: "*"
        exclude: shutdown
  metrics:
    web:
      server:
        auto-time-requests: true

# Spring properties.
spring:

  # Logs.
  output:
    ansi:
      enabled: ALWAYS

  # Spring Boot Admin custom properties, extend Spring Boot ones.
  boot:
    admin:
      notify:
        mail:
          to: angelpinazo@gmail.com # Comma-delimited list of mail recipients of Admin notifications.

  # Mail configuration.
  # If configured, Admin will send email notifications.
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: xxxxxxxxxxxxxxxxxxxxxxx # Replace by your key.
    protocol: smtp
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.sendgrid.net
