# Default configuration.

# General info used by Actuator in the /info endpoint.
info:
  build:
    version: @project.version@
    artifactId: @project.artifactId@
    groupId: @project.groupId@
    name: discovery-server
    description: ${info.build.name} is the discovery server in the cloud.

# Server.
server:
  port: 8761 # De facto standard port for Eureka.
  compression:
    enabled: true # Enable compression for html, xml, css and plain text.

# Actuator.
management:
  endpoints:
    web:
      base-path: /actuator
      enabled-by-default: true
      exposure:
        include: "*"
        exclude: shutdown
  metrics:
    web:
      server:
        auto-time-requests: true

# Eureka discovery server.
eureka:
  client:
    # Both false to avoid this error: "Cannot execute request on any known server".
    registerWithEureka: true # Whether the server will try to register itself as a client.
    fetchRegistry: false # True to get the Eureka registry on startup.

# Spring Framework properties.
spring:

  # Logs.
  output:
    ansi:
      enabled: ALWAYS

# Logging configuration.
logging:
  level:
    es.apinazo: TRACE
    root: INFO
  file: /var/log/cloudsample/discovery.log
  file.max-history: 1
  file.max-size: 2MB
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
